config/routes.rb
Rails.application.routes.draw do
  get 'services/index'

  get 'services/show'

  get 'services/new'

  get 'services/edit'

  get 'stores/index'

  get 'stores/show'

  get 'stores/new'

  get 'stores/edit'
  
  resources :stores, :services
  namespace 'api' do
    namespace 'v1' do
        resources :stores
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/service.rb
class Service < ApplicationRecord
    belongs_to :store
    validates :service, presence: true
end

app/models/store.rb
class Store < ApplicationRecord
    has_many :services, dependent: :destroy 
    validates :name, presence: true
    validates :address, presence: true
    def to_s
        "#{name}"
      end
end

app/controllers/api/v1/stores_controller.rb
class Api::V1::StoresController < ActionController::API
    def index 
        stores = StoresService.new.index(params)
        render json:stores
        
    end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  before_action :current_service, only: [:show, :edit, :update, :destroy]

  def index
    @services = Service.all
  end

  def show

  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.create(service_params)

    redirect_to service_path(@service)
  end

  def edit

  end

  def update
    @service.update(service_params)

    redirect_to service_path(@service)
  end

  def destroy
    @service.destroy

    redirect_to services_path
  end

  private
  def service_params
    params.require(:service).permit(:service, :price, :working_hours, :store_id)
  end

  def current_service
    @service = Service.find(params[:id])
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :current_store, only: [:show, :edit, :update, :destroy]
  def index
    @stores = Store.all
  end

  def show

  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.create(store_params)

    redirect_to store_path(@store)
  end

  def edit

  end

  def update
    @store.update(store_params)

    redirect_to store_path(@store)
  end

  def destroy
    @store.destroy

    redirect_to stores_path
  end

  private
  def store_params
    params.require(:store).permit(:name, :address)
  end

  def current_store
    @store = Store.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorAssignmnet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/services/edit.html.erb
<h3>Update Service Details</h3>
<%= form_with model: @service do |form| %>
  <%= form.text_field :service, placeholder: "service name" %>
  <%= form.number_field :price, placeholder: "price" %>
  <%= form.number_field :working_hours, placeholder: "working hours" %>

  <p>Store: <%= form.select :store_id, Store.all.map { |store| [ store.to_s, store.id ] } %></p>
  <%= form.submit %>
<% end %>

app/views/services/index.html.erb
<table>
  <% @services.each do |service| %>
    <tr>
      <td><%= link_to service.service, service_path(service) %></td>
      <td><%= button_to 'Edit', edit_service_path(service), method: 'get'%></td>
      <td><%= button_to 'Remove', service_path(service), method: 'delete', data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>
<%= link_to "Add a New Service", new_service_path %>

app/views/services/new.html.erb
<h3>New Service Details</h3>
<%= form_with model: @service do |form| %>
  <%= form.text_field :service, placeholder: "service name" %>
  <%= form.number_field :price, placeholder: "price" %>
  <%= form.number_field :working_hours, placeholder: "working hours" %>

  <p>Store: <%= form.select :store_id, Store.all.map { |store| [ store.to_s, store.id ] } %></p>
  <%= form.submit %>
<% end %>

app/views/services/show.html.erb
<%= link_to 'Remove', @service, method: :delete, data: { confirm: 'Are you sure?' } %>

<h1><%= @service.service %></h1>
<h4>Price: <%= @service.price%></h4>
<h4>Working Hours: <%= @service.working_hours%></h4>

app/views/stores/edit.html.erb
<h3>Edit Store</h3>
<%= form_with model: @store do |form| %>
  <p> Name: <%= form.text_field :name %></p>
  <p> Address: <%= form.text_field :address %></p>

  <%= form.submit %>
<% end %>

app/views/stores/index.html.erb
<h1>List of Stores</h1>
<ul><% @stores.each do |store| %>
  <li>
    <%= link_to store.to_s, store_path(store) %>
  <% end %></li>
</ul>

<div><%= link_to 'Create Store', new_store_path %></div>

app/views/stores/new.html.erb
<h3>Add Store</h3>
<%= form_with model: @store do |form| %>
  <p> Name: <%= form.text_field :name %></p>
  <p> Address: <%= form.text_field :address %></p>
  

  <%= form.submit %>
<% end %>

app/views/stores/show.html.erb
<h1><%= @store.to_s %></h1>
<%= link_to 'Edit', edit_store_path(@store) %>

<p><b>Name:</b> <%= @store.name %></p>
<p><b>Address:</b> <%= @store.address %></p>


<h3>Services</h3>
<ul>
  <% @store.services.each do |service| %>
  <li><%= link_to service.service, service_path(service) %></li>
  <% end %>
</ul><br>

<p><%= link_to 'Delete', @store, method: 'delete', data: { confirm: 'Are you sure?' }%></p>
<p><%= link_to 'Go back to all stores', stores_path %></p>